### ISSUE TITLE
Could you create a tag for the release?

### ISSUE THREAD

**Issue by byjg** [heera/iconfig#2]
A project with no tags on packagist requires you use dev-master. But If I have a project that depends on yours I have to add the tag minimum-stability in order to work. 

Create this will take no more than 5 minutes. 

```
git tag 1.0.0
git push --tags
```

And the packagist will auto-update. 

Thank you.

**Comment by heera** [comment]
I'll do it soon. I didn't check it in a while. Thanks :+1:

**Comment by heera** [comment]
Did it @byjg

**Comment by byjg** [comment]
Thank you @heera :)
